CREATE TABLE login_audit (
    audit_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR2(50) NOT NULL,
    attempt_time  DATE DEFAULT SYSDATE,
    status        VARCHAR2(10) CHECK (status IN ('SUCCESS', 'FAILED')),
    ip_address    VARCHAR2(50)
);

CREATE TABLE security_alerts (
    alert_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          VARCHAR2(50) NOT NULL,
    failed_attempts   NUMBER NOT NULL,
    alert_time        DATE DEFAULT SYSDATE,
    alert_message     VARCHAR2(200),
    contact_email     VARCHAR2(100)
);
CREATE OR REPLACE TRIGGER trg_login_failed
AFTER INSERT ON login_audit
FOR EACH ROW
WHEN (NEW.status = 'FAILED')
DECLARE
    v_failed_count NUMBER;
BEGIN
    -- Count failed attempts for same user today
    SELECT COUNT(*)
    INTO v_failed_count
    FROM login_audit
    WHERE username = :NEW.username
      AND status = 'FAILED'
      AND TRUNC(attempt_time) = TRUNC(SYSDATE);

    -- If failed attempts > 2, raise an alert
    IF v_failed_count > 2 THEN
        INSERT INTO security_alerts (
            username,
            failed_attempts,
            alert_message,
            contact_email
        ) VALUES (
            :NEW.username,
            v_failed_count,
            'Suspicious login activity detected: more than 2 failed attempts.',
            'security-team@company.com'
        );
    END IF;
END;
/
SELECT table_name FROM user_tables;
SHOW USER;

INSERT INTO login_audit (username, status) VALUES ('keza', 'FAILED');
DROP TRIGGER trg_login_failed;
CREATE OR REPLACE TRIGGER trg_login_failed
FOR INSERT ON login_audit
COMPOUND TRIGGER

    TYPE t_users IS TABLE OF VARCHAR2(50);
    failed_users t_users := t_users();

AFTER EACH ROW IS
BEGIN
    -- Store usernames with FAILED status
    IF :NEW.status = 'FAILED' THEN
        failed_users.EXTEND;
        failed_users(failed_users.LAST) := :NEW.username;
    END IF;
END AFTER EACH ROW;

AFTER STATEMENT IS
    v_failed_count NUMBER;
BEGIN
    -- Check failed attempts for each user recorded in this statement
    FOR i IN 1 .. failed_users.COUNT LOOP
        
        SELECT COUNT(*)
        INTO v_failed_count
        FROM login_audit
        WHERE username = failed_users(i)
          AND status = 'FAILED'
          AND TRUNC(attempt_time) = TRUNC(SYSDATE);

        IF v_failed_count > 2 THEN
            INSERT INTO security_alerts (
                username,
                failed_attempts,
                alert_message,
                contact_email
            ) VALUES (
                failed_users(i),
                v_failed_count,
                'Suspicious login activity detected: more than 2 failed attempts.',
                'security-team@company.com'
            );
        END IF;

    END LOOP;
END AFTER STATEMENT;

END trg_login_failed;
/

INSERT INTO login_audit (username, status) VALUES ('keza', 'FAILED');
INSERT INTO login_audit (username, status) VALUES ('keza', 'FAILED');
INSERT INTO login_audit (username, status) VALUES ('keza', 'FAILED'); 

SELECT * FROM security_alerts;
-- alert triggers










